feat: add horizontal stepper component
vimwitch/uikit pull request #15
Opened 2022-03-22 07:44 UTC by tkmct

Added horizontal stepper component

2022-03-22 14:37 UTC, vimwitch requested changes
Looks sick!

2022-03-22 14:37 UTC, vimwitch commented on packages/kit/src/Stepper.js
> +      {[...Array(maxStep).keys()].map((v) => (
This seems complicated, could just do `Array(maxStep).fill().map((v) =>`

2022-03-22 14:37 UTC, vimwitch commented on packages/kit/src/stepper.css
> +  color: var(--color-gray-2);
Maybe make this a bit lighter? It's sorta hard to read in darkmode. Maybe color: white and background: gray 6? @ChialiTsai 

![image](https://user-images.githubusercontent.com/631020/159507070-83ee5cf3-1380-4d60-9f4a-54351f25e2fb.png)

2022-03-22 15:35 UTC, vimwitch commented
It would be cool if each step could have a description. Maybe shown on mouseover or as text beneath the number/circle.

@ChialiTsai What do you think of descriptions for steps?

2022-03-22 15:48 UTC, tkmct commented on packages/kit/src/Stepper.js
> +      {[...Array(maxStep).keys()].map((v) => (
Thank you, didn't know that!

2022-03-23 03:24 UTC, vimwitch commented
Changes look good to me

2022-03-23 03:25 UTC, vimwitch approved these changes

2022-03-23 03:25 UTC, merged