feat: add toggle switch component
vimwitch/uikit pull request #20
Opened 2022-03-29 07:31 UTC by tkmct

Added a toggle switch component.
I'm not very fun of having `id` as a prop, but we need to have id hook like [this](https://github.com/facebook/react/pull/22644) to omit that. For now, I think it's okay to have `id` prop for simplicity.

close #18

2022-03-29 15:07 UTC, vimwitch requested changes

2022-03-29 15:07 UTC, vimwitch commented on packages/kit/src/ToggleSwitch.js
> +        id={id}
The id value should default to a strong random value so the user doesn't have to worry about it. I'd recommend adding the `nanoid` package and using a value generated by that.

2022-03-29 15:07 UTC, vimwitch commented on packages/kit/src/ToggleSwitch.js
> +        id={id}
Actually we can get rid of the `id` prop by using `appearance: none` and removing the label element like [this](https://github.com/tkmct/uikit/compare/component/toggle...vimwitch:switch-refactor?expand=1). Funny enough the check from the checkbox component appears now. Another good reason for #19

2022-03-29 15:08 UTC, vimwitch commented
Also what do you think of changing the filename/import to just `Toggle`?

The element looks really good!

2022-03-30 03:25 UTC, tkmct commented on packages/kit/src/ToggleSwitch.js
> +        id={id}
oh, this is interesting approach. I didn't come up with this idea. But it looks simpler and cleaner.
yeah, `appearance: none` is very useful when styling these types of components.
Thanks!!

2022-03-30 15:03 UTC, vimwitch approved these changes

2022-03-30 15:03 UTC, merged